@startuml
scale 3
package com.example.progettoingsw.DTO{

    class AcquirenteDTO {
            -indirizzo_email: String
            -nome: String
            -cognome: String
            -password: String
            -bio: String
            -link: String
            -areageografica: String
            +AcquirenteDTO()
            +AcquirenteDTO(nome: String, cognome: String, indirizzo_email: String, password: String, bio: String, areageografica: String, link: String)
            +getIndirizzo_email(): String
            +setIndirizzo_email(indirizzo_email: String): void
            +getNome(): String
            +setNome(nome: String): void
            +getCognome(): String
            +setCognome(cognome: String): void
            +getPassword(): String
            +setPassword(password: String): void
            +getBio(): String
            +setBio(bio: String): void
            +getLink(): String
            +setLink(link: String): void
            +getAreageografica(): String
            +setAreageografica(areageografica: String): void
    }
    class Asta_allinglese_DTO {
            -id: Long
            -nome: String
            -descrizione: String
            -path_immagine: String
            -baseAsta: float
            -intervalloTempoOfferte: String
            -intervalloOfferteBase: String
            -rialzoMin: float
            -prezzoAttuale: float
            -condizione: String
            -id_venditore: String
            +Asta_allinglese_DTO()
            +Asta_allinglese_DTO(id: Long, nome: String, descrizione: String, path_immagine: String, baseAsta: float,
             intervalloTempoOfferte: String, intervalloOfferteBase: String, rialzoMin: float, prezzoAttuale: float, condizione: String, id_venditore: String)
            +Asta_allinglese_DTO(nome: String, descrizione: String, path_immagine: String, baseAsta: float,
             intervalloTempoOfferte: String, intervalloOfferteBase: String, rialzoMin: float, prezzoAttuale: float, condizione: String, id_venditore: String)
            +getId(): Long
            +setId(id: Long): void
            +getNome(): String
            +setNome(nome: String): void
            +getDescrizione(): String
            +setDescrizione(descrizione: String): void
            +getPath_immagine(): String
            +setPath_immagine(path_immagine: String): void
            +getBaseAsta(): float
            +setBaseAsta(baseAsta: float): void
            +getIntervalloTempoOfferte(): String
            +setIntervalloTempoOfferte(intervalloTempoOfferte: String): void
            +getIntervalloOfferteBase(): String
            +setIntervalloOfferteBase(intervalloOfferteBase: String): void
            +getRialzoMin(): float
            +setRialzoMin(rialzoMin: float): void
            +getPrezzoAttuale(): float
            +setPrezzoAttuale(prezzoAttuale: float): void
            +getCondizione(): String
            +setCondizione(condizione: String): void
            +getId_venditore(): String
            +setId_venditore(id_venditore: String): void
    }
    class Asta_alribasso_DTO {
            -id: Long
            -nome: String
            -descrizione: String
            -path_immagine: String
            -prezzoBase: float
            -intervalloDecrementale: String
            -intervalloBase: String
            -decrementoAutomaticoCifra: float
            -prezzoMin: float
            -prezzoAttuale: float
            -condizione: String
            -id_venditore: String
            +Asta_alribasso_DTO()
            +Asta_alribasso_DTO(id: Long, nome: String, descrizione: String, path_immagine: String, prezzoBase: float, intervalloDecrementale: String,
             intervalloBase: String, decrementoAutomaticoCifra: float, prezzoMin: float, prezzoAttuale: float, condizione: String, id_venditore: String)
            +Asta_alribasso_DTO(nome: String, descrizione: String, path_immagine: String, prezzoBase: float, intervalloDecrementale: String,
             intervalloBase: String, decrementoAutomaticoCifra: float, prezzoMin: float, prezzoAttuale: float, condizione: String, id_venditore: String)
            +getId(): Long
            +setId(id: Long): void
            +getNome(): String
            +setNome(nome: String): void
            +getDescrizione(): String
            +setDescrizione(descrizione: String): void
            +getPath_immagine(): String
            +setPath_immagine(path_immagine: String): void
            +getPrezzoBase(): float
            +setPrezzoBase(prezzoBase: float): void
            +getIntervalloDecrementale(): String
            +setIntervalloDecrementale(intervalloDecrementale: String): void
            +getIntervalloBase(): String
            +setIntervalloBase(intervalloBase: String): void
            +getDecrementoAutomaticoCifra(): float
            +setDecrementoAutomaticoCifra(decrementoAutomaticoCifra: float): void
            +getPrezzoMin(): float
            +setPrezzoMin(prezzoMin: float): void
            +getPrezzoAttuale(): float
            +setPrezzoAttuale(prezzoAttuale: float): void
            +getCondizione(): String
            +setCondizione(condizione: String): void
            +getId_venditore(): String
            +setId_venditore(id_venditore: String): void
    }
    class Asta_inversa_DTO {
            -id: Long
            -nome: String
            -descrizione: String
            -path_immagine: String
            -prezzoMax: float
            -prezzoAttuale: float
            -dataDiScadenza: String
            -condizione: String
            -id_acquirente: String
            +Asta_inversa_DTO()
            +Asta_inversa_DTO(id: Long, nome: String, descrizione: String, path_immagine: String, prezzoMax: float,
             prezzoAttuale: float, dataDiScadenza: String, condizione: String, id_acquirente: String)
            +Asta_inversa_DTO(nome: String, descrizione: String, path_immagine: String, prezzoMax: float,
             prezzoAttuale: float, dataDiScadenza: String, condizione: String, id_acquirente: String)
            +getId(): Long
            +setId(id: Long): void
            +getNome(): String
            +setNome(nome: String): void
            +getDescrizione(): String
            +setDescrizione(descrizione: String): void
            +getPath_immagine(): String
            +setPath_immagine(path_immagine: String): void
            +getPrezzoMax(): float
            +setPrezzoMax(prezzoMax: float): void
            +getPrezzoAttuale(): float
            +setPrezzoAttuale(prezzoAttuale: float): void
            +getDataDiScadenza(): String
            +setDataDiScadenza(dataDiScadenza: String): void
            +getCondizione(): String
            +setCondizione(condizione: String): void
            +getId_acquirente(): String
            +setId_acquirente(id_acquirente: String): void
    }
    class NotificheAcquirente_DTO {
            -id: Long
            -titolo: String
            -commento: String
            -idAcquirente: String
            +NotificheAcquirente_DTO()
            +NotificheAcquirente_DTO(id: Long, titolo: String, commento: String, idAcquirente: String)
            +getId(): Long
            +setId(id: Long): void
            +getTitolo(): String
            +setTitolo(titolo: String): void
            +getCommento(): String
            +setCommento(commento: String): void
            +getIdAcquirente(): String
            +setIdAcquirente(idAcquirente: String): void
    }
     class NotificheVenditore_DTO {
            -id: Long
            -titolo: String
            -commento: String
            -idVenditore: String
            +NotificheVenditore_DTO()
            +NotificheVenditore_DTO(id: Long, titolo: String, commento: String, idVenditore: String)
            +getId(): Long
            +setId(id: Long): void
            +getTitolo(): String
            +setTitolo(titolo: String): void
            +getCommento(): String
            +setCommento(commento: String): void
            +getIdVenditore(): String
            +setIdVenditore(idVenditore: String): void
    }
    class SocialAcquirenteDTO {
            -nome: String
            -link: String
            -indirizzo_email: String
            +SocialAcquirenteDTO(nome: String, link: String, indirizzo_email: String)
            +getNome(): String
            +setNome(nome: String): void
            +getLink(): String
            +setLink(link: String): void
            +getIndirizzo_email(): String
            +setIndirizzo_email(indirizzo_email: String): void
    }
    class SocialVenditoreDTO {
            -nome: String
            -link: String
            -indirizzo_email: String
            +SocialVenditoreDTO(nome: String, link: String, indirizzo_email: String)
            +getNome(): String
            +setNome(nome: String): void
            +getLink(): String
            +setLink(link: String): void
            +getIndirizzo_email(): String
            +setIndirizzo_email(indirizzo_email: String): void
    }
    class VenditoreDTO {
            -indirizzo_email: String
            -nome: String
            -cognome: String
            -password: String
            -bio: String
            -link: String
            -areageografica: String
            +VenditoreDTO()
            +VenditoreDTO(nome: String, cognome: String, indirizzo_email: String, password: String, bio: String, areageografica: String, link: String)
            +getIndirizzo_email(): String
            +setIndirizzo_email(indirizzo_email: String): void
            +getNome(): String
            +setNome(nome: String): void
            +getCognome(): String
            +setCognome(cognome: String): void
            +getPassword(): String
            +setPassword(password: String): void
            +getBio(): String
            +setBio(bio: String): void
            +getLink(): String
            +setLink(link: String): void
            +getAreageografica(): String
            +setAreageografica(areageografica: String): void
    }


}

@enduml